# Les bases pour commencer en Python #

### 1. Les listes ###

Les listes permettent de regrouper des séries de mesures et de les manipuler par la suite.
ATTENTION : il existe deux méthodes courantes pour créer des listes dans un programme Python. Les comportements sont différents et détaillés dans la suite.

**Listes Python natives**

In [2]:
X = []  # Création d'une liste vide
temperatures = [20.2, 15.6, 10.3, 8.4, 17.9, 6.6]  # Liste de 6 valeurs numérotées de 0 à 5
longueur=len(temperatures)
print(temperatures)  # affiche la liste
print(longueur)  # affiche le nombre de termes de la liste
print(temperatures[longueur-1])  # affiche le dernier terme de la liste
temp_reelle=[]
# pour effectuer un calcul sur tous les termes d'une liste Python :
for i in range(len(temperatures)):  # i varie de 0 à longueur-1
    temp_reelle.append(temperatures[i]-2)
print(temp_reelle)

[20.2, 15.6, 10.3, 8.4, 17.9, 6.6]
6
6.6
[18.2, 13.6, 8.3, 6.4, 15.899999999999999, 4.6]


On peut modifier une valeur dans une liste :

In [3]:
temperatures[4] = 7.9  # On modifie la 5ème valeur
print(temperatures)

[20.2, 15.6, 10.3, 8.4, 7.9, 6.6]


On peut ajouter une valeur à une liste :

In [4]:
temperatures.append(3.3)  # On ajoute la valeur 3.3 à la fin de la liste
print(temperatures)

[20.2, 15.6, 10.3, 8.4, 7.9, 6.6, 3.3]


Connaître la longeur d'une liste :

In [5]:
print(len(temperatures))

7


Afficher __la dernière valeur__ d'une liste :

In [6]:
print(temperatures[-1])

3.3


Supprimer une valeur particulière :

In [7]:
temperatures.pop(1)  # On supprime la deuxième valeur
print(temperatures)

[20.2, 10.3, 8.4, 7.9, 6.6, 3.3]


### 2. Les tableaux ###

**Créer et manipuler des tableaux avec numpy**

numpy est une bibliothèque permettant d'effectuer des calculs et de créer des tableaux de valeurs.
On commence par l'importer :

In [9]:
import numpy as np  # numpy est importée et appelée par le nom court np

Création de la liste :

In [10]:
temperatures = np.array([20.2, 15.6, 10.3, 8.4, 17.9, 6.6])
print(temperatures)
# Avec numpy, il est rapide d'effectuer un calcul sur tous les termes d'une liste (pas besoin de boucle)
temp_reelle = temperatures - 2
print(temp_reelle)

[20.2 15.6 10.3  8.4 17.9  6.6]
[18.2 13.6  8.3  6.4 15.9  4.6]


Ajout d'une valeur en fin de tableau :

In [11]:
temperatures = np.append(temperatures, 6.7)
print(temperatures)

[20.2 15.6 10.3  8.4 17.9  6.6  6.7]


Supprimer une valeur particulière

In [12]:
temperatures = np.delete(temperatures, 2)  # supprime la valeur de rang 2 dans la liste, donc la troisième valeur
print(temperatures)

[20.2 15.6  8.4 17.9  6.6  6.7]


Inserer une valeur à une position donnée

In [13]:
temperatures = np.insert(temperatures, 4, 30.25)  # Insère la température 30.25 à la position 4 dans la liste
print(temperatures)

[20.2  15.6   8.4  17.9  30.25  6.6   6.7 ]


**FONDAMENTAL - Différences de comportements entre les tableaux et les listes**

Les cellules ci-dessous montrent les différences de comportements des listes créées nativement ou via numpy.

In [14]:
# Addition de deux listes créées nativement
A = [2, 3]
B = [5, 6]
C = A + B
print("Addition des deux listes : ", C)
# Produit
C = A * 3
print("Produit par un entier : ", C)

Addition des deux listes :  [2, 3, 5, 6]
Produit par un entier :  [2, 3, 2, 3, 2, 3]


In [15]:
# Addition de deux tableaux créées avec numpy
import numpy as np
A = np.array([2, 3])
B = np.array([5, 6])
print("A : ", A)
print("B : ", B)
C = A + B
print("Somme des deux listes : ", C)
# Multiplication
C = A * 3
print("Produit par un nombre : ", C)
C = A * B
print("Produit des deux listes : ", C)
C = A ** 2
print("Élévation au carré de chaque terme : ", C)

A :  [2 3]
B :  [5 6]
Somme des deux listes :  [7 9]
Produit par un nombre :  [6 9]
Produit des deux listes :  [10 18]
Élévation au carré de chaque terme :  [4 9]


Pour effectuer des opérations sur tous les termes d'une liste créée nativement dans Python, il faut passer par une **boucle**.<br>
L'exemple ci-dessous additionne terme à terme deux listes et élève chaque terme au carré.

In [16]:
A = [2, 3]
B = [5, 6]
# Addition des termes
C = []
for i in range(len(A)):
    C.append(A[i]+B[i])
print("Addition de chaque terme : ", C)
# Élévation au carré
C = []
for i in range(len(A)):
    C.append(A[i] ** 2)
print("Élévation des termes au carré : ", C)

Addition de chaque terme :  [7, 9]
Élévation des termes au carré :  [4, 9]


**Créer des tableaux avec linspace et arange**

Exemple avec la fonction linespace(début, fin, nbre de valeurs)

In [17]:
import numpy as np
x = np.linspace(0, 5, 21)
print("x : ",x)

x :  [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25
 3.5  3.75 4.   4.25 4.5  4.75 5.  ]


Exemple avec la fonction arange(début, fin, pas)

In [20]:
import numpy as np
x = np.arange(0, 10, 1)
print("x : ",x)

x :  [0 1 2 3 4 5 6 7 8 9]


### 3. Les boucles ###


Les boucles permettent d'effectuer des tâches répétitives, soit avec un nombre prédéfini d'itérations, soit avec une condition de sortie de boucle.
Dans les cellules qui suivent, remarquez *l'indentation* des lignes qui permet de distinguer les commandes comprises dans la boucle de celles qui sont en dehors.

**Les boucles for**

Elles sont utiles quand le nombre d'itérations est déterminé à l'avance.

Ci-dessous, on affiche i **de 0 jusqu'à 9**.

In [21]:
for i in range (10):
    print(i)

0
1
2
3
4
5
6
7
8
9


On peut aussi ne pas compter de 1 en 1 :

In [22]:
for i in range(0, 10, 3):
    print(i)

0
3
6
9


On peut s'en servir pour parcourir le contenu d'une liste :

In [23]:
for temp in temperatures:
    print("Température en kelvins :", temp + 273.15)

Température en kelvins : 293.34999999999997
Température en kelvins : 288.75
Température en kelvins : 281.54999999999995
Température en kelvins : 291.04999999999995
Température en kelvins : 303.4
Température en kelvins : 279.75
Température en kelvins : 279.84999999999997


**Les boucles while**

Elles sont utilisées avec des conditions: tant que la condition est vraie, on répette les instruction (boucle non bornée).

In [26]:
from random import randint
de = randint(1, 6)  # On tire un dé 6 faces
while de != 6:  # Tant que de est différent (!=) de 6
    print("Pas de 6 :(")
    de = randint(1, 6)
print("J'ai fait un 6 !!! o)")

Pas de 6 :(
Pas de 6 :(
Pas de 6 :(
Pas de 6 :(
Pas de 6 :(
J'ai fait un 6 !!! o)


### 4. Les conditions

Elles permettent d'exécuter des instructions selon qu'une condition est remplie ou non.
Reprenons l'exemple du jeu de dés.

In [27]:
from random import randint
de1 = randint(1, 6)  # Dé tiré par le joueur 1
de2 = randint(1, 6)  # Dé tiré par le joueur 2
if de1 > de2 :
    print("Le joueur 1 a gagné !")
elif de1 == de2 :
    print("Partie nulle !")
else :
    print("Le joueur 2 a gangé !")

Le joueur 2 a gangé !


### 5. Les fonctions ###

Il est possible de définir des fonctions qui ne sont pas présentes initialement dans l'environnement Python.
Une fonction peut soit :
* renvoyer une valeur (return),
* effectuer des actions (tracer des courbes, par exemple).
L'exemple ci-dessous définit une fonction qui renvoie la concentration.

In [ ]:
def concentration(n, V):  # On donne le nom de la fonction et ses paramètres
    return n/V

Elle peut maintenant être utilisée pour effectuer des calculs.

In [ ]:
# Pour affecter une valeur à une variable
c = concentration(0.5, 0.75)
print(c)

# Pour un affichage direct
print(concentration(0.25, 1.5))